language: node_js
node_js:
- '4'
sudo: required
services:
- docker
before_script: ./scripts/install-dependencies.sh && ./scripts/docker-build-images.sh
deploy:
  provider: script
  script: ./scripts/docker-internal-release.sh
  on:
    branch: master
notifications:
  email:
    recipients:
    - ladislav@apiary.io
    on_success: change
    on_failure: always
env:
  global:
  - secure: WdYzwScmMKy9ZWSDKwX9DzCI3dD1UIWJaNk3h/uu7MaAlQ9khMIIHl4FlXNQafUcWBTVKKPXbsI+AR4Z4LVUJ2LeHnDC2wYt+GbJo8gB9r5MsT8kS/A/BWJpt4TsFcbG/eSLr80YuR1a5MyKtD7tYVsaxMmJvu2x8hIaY/BmVow=
