language: node_js
node_js:
  - "4"
sudo: required

services:
  - docker

install: ./scripts/install-dependencies.sh

script: ./scripts/docker-build-images.sh

notifications:
  email:
    recipients:
      - ladislav@apiary.io
    on_success: change
    on_failure: always

