version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: Install the dependencies
          command: npm install dockerlint
      - run:
          name: add dockerlint to path
          command: |
            echo 'export PATH=./node_modules/.bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Check Dockerfiles
          command: "./scripts/test.sh"
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build the images
          command: ./scripts/docker-build-images.sh

  deploy:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build the images
          command: ./scripts/docker-build-images.sh
      - run:
          name: Copy image list to /tmp
          command: cp $CIRCLE_WORKING_DIRECTORY/images /tmp/ || true
      - run:
          name: Release docker images
          command: ./scripts/docker-internal-release.sh
      - run:
          name: Cleanup containers, volumes and built images
          command: ./scripts/cleanup.sh || true

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build:
          requires:
            - lint
          filters:
            branches:
              ignore: master
      - deploy:
          requires:
            - lint
          filters:
            branches:
              only: master
